# Generated by Django 5.2.5 on 2025-08-26 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('vendas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('reuniao', 'Reunião'), ('ligacao', 'Ligação'), ('visita', 'Visita'), ('apresentacao', 'Apresentação'), ('evento', 'Evento'), ('outro', 'Outro')], default='reuniao', max_length=15, verbose_name='Tipo')),
                ('data_inicio', models.DateTimeField(verbose_name='Data/Hora de Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data/Hora de Fim')),
                ('dia_inteiro', models.BooleanField(default=False, verbose_name='Dia Inteiro')),
                ('local', models.CharField(blank=True, max_length=300, null=True, verbose_name='Local')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('lembrete', models.BooleanField(default=True, verbose_name='Criar Lembrete')),
                ('minutos_lembrete', models.IntegerField(default=15, verbose_name='Minutos antes do lembrete')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('oportunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.oportunidade', verbose_name='Oportunidade')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
                ('participantes', models.ManyToManyField(blank=True, related_name='eventos_participando', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Evento da Agenda',
                'verbose_name_plural': 'Eventos da Agenda',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligação'), ('email', 'E-mail'), ('reuniao', 'Reunião'), ('visita', 'Visita'), ('proposta', 'Elaborar Proposta'), ('follow_up', 'Follow-up'), ('apresentacao', 'Apresentação'), ('outro', 'Outro')], default='outro', max_length=15, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('adiada', 'Adiada')], default='pendente', max_length=15, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridade')),
                ('data_vencimento', models.DateTimeField(verbose_name='Data de Vencimento')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('tempo_estimado', models.IntegerField(blank=True, null=True, verbose_name='Tempo Estimado (minutos)')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('lembrete', models.BooleanField(default=False, verbose_name='Criar Lembrete')),
                ('data_lembrete', models.DateTimeField(blank=True, null=True, verbose_name='Data do Lembrete')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('oportunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.oportunidade', verbose_name='Oportunidade')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['data_vencimento', '-prioridade'],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligação Realizada'), ('email_enviado', 'E-mail Enviado'), ('email_recebido', 'E-mail Recebido'), ('reuniao', 'Reunião'), ('visita', 'Visita'), ('proposta_enviada', 'Proposta Enviada'), ('contrato_assinado', 'Contrato Assinado'), ('pagamento_recebido', 'Pagamento Recebido'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Tipo')),
                ('data_atividade', models.DateTimeField(verbose_name='Data da Atividade')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('oportunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.oportunidade', verbose_name='Oportunidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tarefas.tarefa', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-data_atividade'],
            },
        ),
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='tarefas.tarefa', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Anotação',
                'verbose_name_plural': 'Anotações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
