# Generated by Django 5.2.5 on 2025-08-26 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria')),
                ('unidade_medida', models.CharField(default='UN', max_length=10, verbose_name='Unidade de Medida')),
                ('estoque_atual', models.IntegerField(default=0, verbose_name='Estoque Atual')),
                ('estoque_minimo', models.IntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Oportunidade')),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Estimado')),
                ('probabilidade', models.IntegerField(default=50, verbose_name='Probabilidade (%)')),
                ('status', models.CharField(choices=[('prospectando', 'Prospectando'), ('qualificada', 'Qualificada'), ('proposta', 'Proposta Enviada'), ('negociacao', 'Em Negociação'), ('fechada_ganha', 'Fechada - Ganha'), ('fechada_perdida', 'Fechada - Perdida')], default='prospectando', max_length=20, verbose_name='Status')),
                ('fase_funil', models.CharField(choices=[('inicial', 'Contato Inicial'), ('interesse', 'Demonstrou Interesse'), ('necessidade', 'Identificou Necessidade'), ('orcamento', 'Solicitou Orçamento'), ('decisao', 'Em Decisão'), ('fechamento', 'Fechamento')], default='inicial', max_length=20, verbose_name='Fase do Funil')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fechamento_prevista', models.DateField(verbose_name='Data de Fechamento Prevista')),
                ('data_fechamento_real', models.DateField(blank=True, null=True, verbose_name='Data de Fechamento Real')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('origem', models.CharField(blank=True, max_length=100, null=True, verbose_name='Origem')),
                ('concorrentes', models.TextField(blank=True, null=True, verbose_name='Concorrentes')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número da Venda')),
                ('data_venda', models.DateField(verbose_name='Data da Venda')),
                ('status', models.CharField(choices=[('orcamento', 'Orçamento'), ('pedido', 'Pedido'), ('aprovada', 'Aprovada'), ('faturada', 'Faturada'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], default='orcamento', max_length=15, verbose_name='Status')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('oportunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendas.oportunidade', verbose_name='Oportunidade')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('desconto_item', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto do Item')),
                ('observacoes', models.CharField(blank=True, max_length=300, null=True, verbose_name='Observações')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.produto', verbose_name='Produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Item da Venda',
                'verbose_name_plural': 'Itens da Venda',
            },
        ),
    ]
